name: vlagit_plus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  responsive_grid: ^2.4.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  get_storage: ^2.1.1
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0
  google_mobile_ads: ^8.0.0
  screenshot: ^3.0.0
  share_plus: ^13.0.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.4
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
    - assets/apple-store.png
    - assets/play-store.png
    - shorebird.yaml

  fonts:
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4-Regular.ttf
        - asset: assets/fonts/SourceSerif4-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/SourceSerif4_18pt-SemiBold.ttf
          weight: 600
